//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkSumApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountLog
    {
        public int ID { get; set; }
        public string ParkCardTrace { get; set; }
        public int CardNo { get; set; }
        public int ParkSapceID { get; set; }
        public int CarSizeType { get; set; }
        public string CarPhoto { get; set; }
        public string PlateNumber { get; set; }
        public Nullable<System.DateTime> CardInTime { get; set; }
        public Nullable<System.DateTime> ParkInTime { get; set; }
        public Nullable<System.DateTime> CardOutTime { get; set; }
        public Nullable<System.DateTime> ParkOutTime { get; set; }
        public Nullable<System.DateTime> LastAccountTime { get; set; }
        public double DuePay { get; set; }
        public double ActualPay { get; set; }
        public int PayMethod { get; set; }
        public string CardType { get; set; }
        public string LogOperator { get; set; }
        public int GarageID { get; set; }
        public string Remark { get; set; }
        public string carModelName { get; set; }
        public string inPort { get; set; }
        public string outPort { get; set; }
    }
}
